### ISSUE TITLE
Cannot delete devices

### ISSUE THREAD

**Issue by ihrigb** [ioBroker/ioBroker.devices#194]
**Describe the bug**  
I cannot delete devices from the list.

**To Reproduce**  
1. Create any device
2. Click on the bin
4. See nothing happening

**Expected behavior**  
Confirmation dialog to delete a device

**Screenshots & Logfiles**  
Console Stacktrace:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'background')
    at DialogDeleteFolder.js:22:40
    at Object.create (getStylesCreator.js:19:35)
    at b (makeStyles.js:95:34)
    at makeStyles.js:233:7
    at _ (makeStyles.js:187:14)
    at S (makeStyles.js:225:5)
    at Eo (DialogDeleteFolder.js:48:21)
    at Si (react-dom.production.min.js:167:137)
    at Cs (react-dom.production.min.js:290:337)
    at bl (react-dom.production.min.js:280:389)
    at gl (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at sl (react-dom.production.min.js:273:245)
    at Ha (react-dom.production.min.js:127:105)
    at ul (react-dom.production.min.js:274:266)
    at react-dom.production.min.js:312:443
    at eu (react-dom.production.min.js:313:155)
    at t.render (react-dom.production.min.js:322:90)
    at Zo (DialogDeleteFolder.js:118:12)
    at onClick (ListDevices.js:1629:37)
    at Object.Ne (react-dom.production.min.js:54:317)
    at Ie (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at Fr (react-dom.production.min.js:105:68)
    at Rr (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at ll (react-dom.production.min.js:274:42)
    at Te (react-dom.production.min.js:52:375)
    at Wr (react-dom.production.min.js:109:469)
    at Gt (react-dom.production.min.js:74:59)
    at Ut (react-dom.production.min.js:73:73)
```

**Versions:**  
 - Adapter version: 1.1.0
 - JS-Controller version: 4.0.23
 - Node version: 16.17.1
 - Operating system: buanet docker container

**Comment by GermanBluefox** [comment]
Cannot reproduce with 1.2.0

**Comment by Feuer-sturm** [comment]
@ihrigb Please check with current version 1.2.1
I had no problems on my system. If there is no feedback we will close this issue.
