### ISSUE TITLE
[BUG] "Add state" does not work

### ISSUE THREAD

**Issue by Z18Aplha** [ioBroker/ioBroker.devices#195]
**Describe the bug**  
Adding a state to an existing device does not work.

**To Reproduce**  
1. Create new device or edit an existing one
2. Click on 'Add state'

**Expected behavior**  
A new state appears at the bottom of the list, which can be customized or a popup appears where i can define my new state directly.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/44472284/197603290-368cb081-2c9b-4515-af57-8a9a0f6e69a4.png)

**Versions:**  
 - Adapter version: v1.1.0
 - JS-Controller version: 4.0.23
 - Node version: v16.17.0
 - Operating system: ubuntu 20.04

**Comment by strikegun** [comment]
Is it the same error? 
I can add new states. But after adding it or opening the device, the Admin page gets black.
JS error:
`TypeError: Cannot read properties of undefined (reading 'clsx')
    at n.value (DialogEditDevice.js:1135:44)
    at DialogEditDevice.js:1160:91
    at Array.map (<anonymous>)
    at n.value (DialogEditDevice.js:1160:69)
    at n.value (DialogEditDevice.js:1248:31)
    at Li (react-dom.production.min.js:204:189)
    at bi (react-dom.production.min.js:203:149)
    at yl (react-dom.production.min.js:292:172)
    at Ms (react-dom.production.min.js:280:389)
    at zs (react-dom.production.min.js:280:320)
    at ms (react-dom.production.min.js:280:180)
    at as (react-dom.production.min.js:271:88)
    at ls (react-dom.production.min.js:273:300)
    at Nc (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonymous) @ instrument.ts:124
di @ react-dom.production.min.js:189
n.callback @ react-dom.production.min.js:189
Da @ react-dom.production.min.js:144
Hl @ react-dom.production.min.js:262
Ml @ react-dom.production.min.js:260
gl @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
xs @ react-dom.production.min.js:281
ls @ react-dom.production.min.js:273
Nc @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
DialogEditDevice.js:1135 Uncaught TypeError: Cannot read properties of undefined (reading 'clsx')
    at n.value (DialogEditDevice.js:1135:44)
    at DialogEditDevice.js:1160:91
    at Array.map (<anonymous>)
    at n.value (DialogEditDevice.js:1160:69)
    at n.value (DialogEditDevice.js:1248:31)
    at Li (react-dom.production.min.js:204:189)
    at bi (react-dom.production.min.js:203:149)
    at yl (react-dom.production.min.js:292:172)
    at Ms (react-dom.production.min.js:280:389)
    at zs (react-dom.production.min.js:280:320)
    at ms (react-dom.production.min.js:280:180)
    at as (react-dom.production.min.js:271:88)
    at ls (react-dom.production.min.js:273:300)
    at Nc (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273`

**Comment by LiaraAlis** [comment]
@strikegun I can confirm this. I've tried to add saturation to my rgb light, but got the same error. After adding this new state, edit form is broken.

**Comment by Scrounger** [comment]
i get the following if i try to add a custom state, GUI crashing:

```
Uncaught TypeError: s.default.Utils is undefined
    value DialogEditDevice.js:1135
    children DialogEditDevice.js:1160
    value DialogEditDevice.js:1160
    value DialogEditDevice.js:1248
    React 8
        Li
        bi
        yl
        Ms
        zs
        ms
        as
        cs
    V scheduler.production.min.js:13
    Z scheduler.production.min.js:14
    36813 scheduler.production.min.js:14
    Webpack 12
        n
        45296
        n
        34463
        n
        54164
        n
        1250
        n
        <anonymous>
        <anonymous>
        <anonymous>
DialogEditDevice.js:1135:32
    value DialogEditDevice.js:1135
    children DialogEditDevice.js:1160
    map self-hosted:221
    value DialogEditDevice.js:1160
    value DialogEditDevice.js:1248
    React 8
    cs self-hosted:1406
    V scheduler.production.min.js:13
    Z scheduler.production.min.js:14
    (Async: EventHandlerNonNull)
    36813 scheduler.production.min.js:14
    Webpack 12
        n
        45296
        n
        34463
        n
        54164
        n
        1250
        n
        <anonym>
        <anonym>
        <anonym>
```

after if i try to edit this device, i got the following, GUI is crashing:

```
Uncaught TypeError: s.default.Utils is undefined
    value https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    children https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    value https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    value https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    Li https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    bi https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    yl https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    Ms https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    zs https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    ms https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    as https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    ls https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    Nc https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    rs https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    rs https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    ns https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    enqueueSetState https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    setState https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    value https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    onClick https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    Re https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    Be https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    Er https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    Er https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    Dr https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    Wr https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    ss https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    Te https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    Wr https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    qt https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    Ut https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    Ir https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    Fr https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    Nr https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    Nr https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    createRoot https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    e https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    <anonymous> https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    <anonymous> https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
    <anonymous> https://10.0.120.2:8081/adapter/devices/static/js/main.10538062.js:2
main.10538062.js:2:8372552
```

**Comment by SvenM74** [comment]
ony chance to fix this. I do have the same issue

**Comment by LocoR9** [comment]
I do have the same issue

**Comment by Keven6077** [comment]
Same here.
After add new state, the device manager turns black.
After reload ist, there is only 1 state in the device. A click on the edit button, turns the device manager black again.
![image](https://user-images.githubusercontent.com/59521882/234591111-22860a92-3c0b-4fed-bdd2-b20fbd9c6107.png)

But it is added to the object alias
![image](https://user-images.githubusercontent.com/59521882/234591454-fdfddfea-dcd8-4b6a-9695-a1ae00db253a.png)

**Comment by GermanBluefox** [comment]
Fixed for a while
