### ISSUE TITLE
Completely White Screen (Blank Page) in v1.1.3

### ISSUE THREAD

**Issue by Armilar** [ioBroker/ioBroker.devices#256]
**Describe the bug**  
After I click on devices, all that comes up is a completely blank page

**Screenshots & Logfiles**  
![image](https://github.com/ioBroker/ioBroker.devices/assets/102996011/b098368c-e56a-4697-95bd-7788b32a9648)

**Versions:**  
 - Adapter version: 1.1.3
 - JS-Controller version: 4.0.24
 - Node version: 18.16.0
 - Operating system: Ubuntu 22.04.2 LTS

**Additional context**

**Comment by Apollon77** [comment]
Can you pleas eopen the browser Dev-Tools and check in the console if ou see any errors?

**Comment by Armilar** [comment]
bootstrap.jsx:19 iobroker.admin@6.4.4
instrument.ts:132 [2023-05-17T11:12:42.223Z] Try to connect
content_script.js:1 chrome content script has been inserted
content_script.js:16 start with href http://192.168.1.167:8081/#tab-devices
content_script.js:19 indicate that add on has been installed
content_script.js:21 check if opened window is for submitting to JIRA
content_script.js:26 window name = null
content_script.js:28 opened window is not for submitting to JIRA
instrument.ts:132 Stored version: , new version: 6.4.4
instrument.ts:132 Connected: true
index.js:16 iobroker.devices@1.1.3
Prompt.js:15 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

Prompt.js:16 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
Prompt.js:17 Help us to create open source project with reactJS!
Prompt.js:18 See you :)
socket.io.js:66 [2023-05-17T11:12:45.197Z] Try to connect
instrument.ts:132 TypeError: Cannot read properties of undefined (reading 'clsx')
    at r.value (ListDevices.js:1604:24)
    at ListDevices.js:1779:31
    at Array.map (<anonymous>)
    at r.value (ListDevices.js:1779:14)
    at r.value (ListDevices.js:1871:34)
    at r.value (ListDevices.js:2832:27)
    at Li (react-dom.production.min.js:204:189)
    at ji (react-dom.production.min.js:203:149)
    at ws (react-dom.production.min.js:292:172)
    at xl (react-dom.production.min.js:280:389)
    at gl (react-dom.production.min.js:280:320)
    at zl (react-dom.production.min.js:280:180)
    at ol (react-dom.production.min.js:271:88)
    at al (react-dom.production.min.js:268:429)
    at V (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonym) @ instrument.ts:132
di @ react-dom.production.min.js:189
n.callback @ react-dom.production.min.js:189
Aa @ react-dom.production.min.js:144
Hs @ react-dom.production.min.js:262
xs @ react-dom.production.min.js:260
Ms @ react-dom.production.min.js:259
(anonym) @ react-dom.production.min.js:283
Vl @ react-dom.production.min.js:281
al @ react-dom.production.min.js:270
V @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
ListDevices.js:1604 Uncaught TypeError: Cannot read properties of undefined (reading 'clsx')
    at r.value (ListDevices.js:1604:24)
    at ListDevices.js:1779:31
    at Array.map (<anonymous>)
    at r.value (ListDevices.js:1779:14)
    at r.value (ListDevices.js:1871:34)
    at r.value (ListDevices.js:2832:27)
    at Li (react-dom.production.min.js:204:189)
    at ji (react-dom.production.min.js:203:149)
    at ws (react-dom.production.min.js:292:172)
    at xl (react-dom.production.min.js:280:389)
    at gl (react-dom.production.min.js:280:320)
    at zl (react-dom.production.min.js:280:180)
    at ol (react-dom.production.min.js:271:88)
    at al (react-dom.production.min.js:268:429)
    at V (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
value @ ListDevices.js:1604
(anonym) @ ListDevices.js:1779
value @ ListDevices.js:1779
value @ ListDevices.js:1871
value @ ListDevices.js:2832
Li @ react-dom.production.min.js:204
ji @ react-dom.production.min.js:203
ws @ react-dom.production.min.js:292
xl @ react-dom.production.min.js:280
gl @ react-dom.production.min.js:280
zl @ react-dom.production.min.js:280
ol @ react-dom.production.min.js:271
al @ react-dom.production.min.js:268
V @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14

![image](https://github.com/ioBroker/ioBroker.devices/assets/102996011/358b780c-be58-4d0e-8e63-80816a067232)
![image](https://github.com/ioBroker/ioBroker.devices/assets/102996011/2b628507-8eb2-48a2-9e60-d223240a3882)

**Comment by crunchip77** [comment]
> Können Sie bitte die Dev-Tools des Browsers öffnen und in der Konsole nachsehen, ob Fehler angezeigt werden?

bei mir ebenfalls
`caught TypeError: Cannot read properties of undefined (reading 'clsx')
instrument.ts:132 TypeError: Cannot read properties of undefined (reading 'clsx')
    at r.value (ListDevices.js:1604:24)
    at ListDevices.js:1779:31
    at Array.map (<anonymous>)
    at r.value (ListDevices.js:1779:14)
    at r.value (ListDevices.js:1871:34)
    at r.value (ListDevices.js:2832:27)
    at Li (react-dom.production.min.js:204:189)
    at ji (react-dom.production.min.js:203:149)
    at ws (react-dom.production.min.js:292:172)
    at xl (react-dom.production.min.js:280:389)
    at gl (react-dom.production.min.js:280:320)
    at zl (react-dom.production.min.js:280:180)
    at ol (react-dom.production.min.js:271:88)
    at al (react-dom.production.min.js:268:429)
    at V (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:132
react-dom.production.min.js:283 Uncaught TypeError: Cannot read properties of undefined (reading 'clsx')
    at r.value (ListDevices.js:1604:24)
    at ListDevices.js:1779:31
    at Array.map (<anonymous>)
    at r.value (ListDevices.js:1779:14)
    at r.value (ListDevices.js:1871:34)
    at r.value (ListDevices.js:2832:27)
    at Li (react-dom.production.min.js:204:189)
    at ji (react-dom.production.min.js:203:149)
    at ws (react-dom.production.min.js:292:172)
    at xl (react-dom.production.min.js:280:389)
    at gl (react-dom.production.min.js:280:320)
    at zl (react-dom.production.min.js:280:180)
    at ol (react-dom.production.min.js:271:88)
    at al (react-dom.production.min.js:268:429)
    at V (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)`

**Comment by Garfonso** [comment]
Ich konnte das Problem bei mir auch reproduzieren. 

Ich hab es auf meinem Fork gefixt. Falls jemand testen möchte, von beliebiger URL installieren und da `https://github.com/Garfonso/ioBroker.devices` einfügen.

**Comment by Garfonso** [comment]
@GermanBluefox 
Ich hab den Fix in meinen PR ( #248 ) hinzugefügt und den rebased und Konflikte gelöst, so dass die Änderungen aus dem Master mit integriert sind und neugebaut (`npm run prepublishOnly` im Hauptordner -> ist das ausreichend? Es funktioniert zumindest für mich :smile:  ).

**Comment by tt-tom17** [comment]
der Fix läuft auch bei mir.

**Comment by klein0r** [comment]
Mit 1.1.5 bekomme ich keine weiße Seite mehr. Kann hier geschlossen werden @Armilar ?

**Comment by Armilar** [comment]
Ja funktioniert

**Comment by Garfonso** [comment]
Danke für die Rückmeldungen. :-)
